version: '3.4'

services:
  maternityhospital.api:
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MaternityHospitalDb;Username=postgres;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro