version: '3.4'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  maternityhospital.api:
    image: ${DOCKER_REGISTRY-}maternityhospitalapi
    build:
      context: .
      dockerfile: MaternityHospital.API/Dockerfile
